# Generated by Django 6.0.4 on 2026-04-23 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
