# Generated by Django 6.0.4 on 2026-04-23 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_alter_airplane_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
