# Generated by Django 6.0.4 on 2026-05-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0003_alter_airplane_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('seat_class', models.CharField(choices=[('first', 'First'), ('business', 'Business'), ('economy', 'Economy')], default='economy', max_length=20)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='aviation.airplane')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('airplane', 'row', 'number'), name='unique_seat_per_airplane')],
            },
        ),
    ]
