# Generated by Django 6.0.4 on 2026-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_user_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
