# Generated by Django 6.0.4 on 2026-05-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0004_seat'),
        ('flights', '0002_flight_flight_number'),
        ('orders', '0002_order_currency_order_total_amount'),
        ('tickets', '0005_ticket_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='aviation.seat'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight', 'seat'), name='unique_ticket_per_flight_seat'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
    ]
