# Generated by Django 6.0.4 on 2026-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_unique_ticket_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='available', max_length=20),
        ),
    ]
