# Generated by Django 6.0.4 on 2026-04-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviation', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='aviation.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='locations.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='locations.airport')),
            ],
        ),
    ]
