# Generated by Django 6.0.4 on 2026-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='FL0000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
