# Generated by Django 6.0.4 on 2026-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.PositiveIntegerField(default=0, help_text='Base price ticket for this flight'),
        ),
    ]
